version: '3'

services:
  db:
    image: mysql:8.1
    hostname: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
    environment:
    - MYSQL_ROOT_PASSWORD=root_pwd
    - MYSQL_DATABASE=keycloak
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=pa55word
    ports:
      - 3306:3306
  db-client:
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin
    - KC_DB=mysql
    - KC_DB_USERNAME=admin
    - KC_DB_PASSWORD=pa55word
    - KC_DB_URL_HOST=mysql  
    - KC_DB_URL_PORT=3306
    - KC_DB_SCHEMA=keycloak
    ports:
      - 8080:8080
    command: ["start-dev","--import-realm"]
    depends_on:
      - db
    restart: on-failure:10
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json